baseURL = "http://designforfab.com/"
languageCode = "en-us"
title = "Tufts ME 93: DFF"
theme = "book"
enableGitInfo = true
[params]
  BookSection = '*'
  BookRepo = 'https://github.com/pingswept/design-for-fab'
  BookEditPath = 'edit/master/content'
[markup.goldmark.renderer]
  unsafe= true
